### ISSUE TITLE
Add support for cross-classpath dependencies

### ISSUE THREAD

**Issue by densh** [scala-native/sbt-crossproject#27]
Discovered while trying to use sbt-crossproject to migrate build for fastparse:

* https://github.com/lihaoyi/fastparse/blob/master/build.sbt#L215

In the original Scala.js cross project they are defined in:

* https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/cross/CrossProject.scala#L363-L369

* https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fscala-js%2Fscala-js%2Fblob%2Fmaster%2Fsbt-plugin%2Fsrc%2Fmain%2Fscala%2Forg%2Fscalajs%2Fsbtplugin%2Fcross%2FCrossClasspathDependency.scala&sa=D&sntz=1&usg=AFQjCNHYli-VdxrWWxc9QbCNez7GSmOyOQ

/cc @MasseGuillaume

**Comment by MasseGuillaume** [comment]
Hum is this something new?

**Comment by densh** [comment]
Anyway we missed it, and it to add it in 0.2 of sbt-crossproject.

**Comment by MasseGuillaume** [comment]
It look like this is available already

https://github.com/scala-native/sbt-crossproject/blob/master/sbt-crossproject/src/main/scala/sbtcrossproject/CrossProject.scala#L158-L164

**Comment by sjrd** [comment]
@MasseGuillaume Those should be in `CrossProjectExtra`, so that they are directly imported in sbt builds. Having them in the companion object of `CrossProject` is not helping, because another implicit conversion defined in sbt has higher priority (but is not applicable due to a missing implicit view).

This only fails if the `CrossProject` (say `foobar`) is used in a `%` dependency, as in `.dependsOn(foobar % "test")`. If it just `.dependsOn(foobar)`, it works fine.

**Comment by sjrd** [comment]
This is a blocker for Scala.js' master branch to migrate to sbt-crossproject.
